<a href="https://colab.research.google.com/github/shu65/theoretical-numerical-linear-algebra/blob/main/%E7%B7%9A%E5%BD%A2%E8%A8%88%E7%AE%97%E3%81%AE%E6%95%B0%E7%90%86_7_2_3_%E3%81%B9%E3%81%8D%E4%B9%97%E6%B3%95%E3%80%80%E6%B8%9B%E6%AC%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np

a_matrix = np.array([
    [1., 0., 0.,],
    [0., 2., 1.,],
    [0., 1., 1.],
])
a_matrix

array([[1., 0., 0.],
       [0., 2., 1.],
       [0., 1., 1.]])

In [51]:
np.linalg.eig(a_matrix)

(array([0.38196601, 2.61803399, 1.        ]),
 array([[ 0.        ,  0.        ,  1.        ],
        [ 0.52573111, -0.85065081,  0.        ],
        [-0.85065081, -0.52573111,  0.        ]]))

In [88]:
def power_method(a, max_iterations=100):
  eigen_vector = np.ones((a.shape[1],))/np.sqrt(a.shape[1]) 
  for i in range(max_iterations):
    y = a @ eigen_vector
    eigen_value = np.linalg.norm(y)
    eigen_vector = y/eigen_value
    print(f"iter:{i} eigen_value:{eigen_value} eigen_vector:{eigen_vector}")
  return eigen_value, eigen_vector

def power_method_n(a, n_eigen_values=1, max_iterations=100):
  n = a.shape[0]
  b = a.copy()
  eigen_values = []
  eigen_vectors = []
  for i in range(n_eigen_values):
    print("new b", b)
    eigen_value, eigen_vector = power_method(b, max_iterations=max_iterations)
    eigen_values.append(eigen_value)
    eigen_vectors.append(eigen_vector)
    b = b - eigen_value * (eigen_vector.reshape(n, 1) @ eigen_vector.reshape(1, n))
  return eigen_values, eigen_vectors

power_method_n(a_matrix, n_eigen_values=2)

new b [[1. 0. 0.]
 [0. 2. 1.]
 [0. 1. 1.]]
iter:0 eigen_value:2.1602468994692874 eigen_vector:[0.26726124 0.80178373 0.53452248]
iter:1 eigen_value:2.5354627641855494 eigen_vector:[0.10540926 0.84327404 0.52704628]
iter:2 eigen_value:2.6055496327817074 eigen_vector:[0.04045567 0.84956906 0.52592371]
iter:3 eigen_value:2.616202818006034 eigen_vector:[0.01546351 0.85049287 0.52575923]
iter:4 eigen_value:2.617766616112355 eigen_vector:[0.00590714 0.85062776 0.52573521]
iter:5 eigen_value:2.6179949751669316 eigen_vector:[0.00225636 0.85064745 0.52573171]
iter:6 eigen_value:2.6180282966503086 eigen_vector:[0.00086185 0.85065032 0.5257312 ]
iter:7 eigen_value:2.6180331582817447 eigen_vector:[3.29199202e-04 8.50650737e-01 5.25731125e-01]
iter:8 eigen_value:2.618033867586182 eigen_vector:[1.25742912e-04 8.50650798e-01 5.25731114e-01]
iter:9 eigen_value:2.6180339710723466 eigen_vector:[4.80295188e-05 8.50650807e-01 5.25731112e-01]
iter:10 eigen_value:2.6180339861707753 eigen_vector:[1.83456437e

([2.618033988749895, 1.0],
 [array([1.15806515e-42, 8.50650808e-01, 5.25731112e-01]),
  array([ 1.00000000e+00, -2.85132643e-42, -1.15338577e-42])])