<a href="https://colab.research.google.com/github/shu65/theoretical-numerical-linear-algebra/blob/main/%E7%B7%9A%E5%BD%A2%E8%A8%88%E7%AE%97%E3%81%AE%E6%95%B0%E7%90%86_7_2_3_%E3%81%B9%E3%81%8D%E4%B9%97%E6%B3%95%E3%80%80%E3%82%B7%E3%83%95%E3%83%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a_matrix = np.array(
    [[1, 0],
     [0, 2]]
     )
a_matrix

array([[1, 0],
       [0, 2]])

In [2]:
np.linalg.eig(a_matrix)

(array([1., 2.]), array([[1., 0.],
        [0., 1.]]))

In [3]:
def lu_decompose(a):
  n = a.shape[0]
  l = a.copy()
  u = np.identity(n)
  for i in range(n):
    for j in range(i + 1, n):
      u[j][i] = l[j][i]/l[i][i]
      for k in range(i + 1, n):
        l[j][k] -= u[j][i] * l[i][k]
    return l, u

l, u = lu_decompose(a_matrix)
print("l", l)
print("u", u)

l [[1 0]
 [0 2]]
u [[1. 0.]
 [0. 1.]]


In [4]:
np.testing.assert_almost_equal(a_matrix, l @ u)

In [5]:
def l_solve(l, x):
  n = len(x)
  v = np.zeros(n)
  a = l.copy()
  b = x.copy()
  for i in range(n):
    tmp = b[i] / a[i, i]
    v[i] = tmp
    for j in range(i+1, n):
      b[j] -= a[j, i] *  tmp
      a[j, i] = 0
  return v

x = np.ones((a_matrix.shape[1],))/np.sqrt(a_matrix.shape[1]) 
v = l_solve(l, x)
v

array([0.70710678, 0.35355339])

In [6]:
np.testing.assert_almost_equal(l @ v, x)

In [7]:
def u_solve(u, v):
  n = len(v)
  y = np.zeros(n)
  a = u.copy()
  b = v.copy()
  for i in reversed(range(n)):
    tmp = b[i] / a[i, i]
    v[i] = tmp
    for j in range(i+1, n):
      b[j] -= a[j, i] *  tmp
      a[j, i] = 0
  return v

x = np.ones((a_matrix.shape[1],))/np.sqrt(a_matrix.shape[1]) 
y = u_solve(u, v)
y

array([0.70710678, 0.35355339])

In [8]:
np.testing.assert_almost_equal(u @ y, v)

In [24]:
def shift_inverse_power_method(a, s, max_iterations=100):
  n = a.shape[0]
  l, u = lu_decompose(a - s*np.identity(n))
  eigen_vector = np.ones((a.shape[1],))/np.sqrt(a.shape[1])
  print("init eigen_vector", eigen_vector)
  for i in range(max_iterations):
    v = l_solve(l, eigen_vector)
    y = u_solve(u, v)
    inversed_eigen_value = np.linalg.norm(y)
    eigen_vector = y/inversed_eigen_value
    print(f"iter:{i} eigen_value:{1.0/inversed_eigen_value} eigen_vector:{eigen_vector}")
  return s + 1.0/inversed_eigen_value, eigen_vector

shift_inverse_power_method(a_matrix, s=0.99)

init eigen_vector [0.70710678 0.70710678]
iter:0 eigen_value:0.014141442500706375 eigen_vector:[0.99995099 0.0099005 ]
iter:1 eigen_value:0.010000490087961673 eigen_vector:[9.99999995e-01 9.80296045e-05]
iter:2 eigen_value:0.010000000048044315 eigen_vector:[1.00000000e+00 9.70590148e-07]
iter:3 eigen_value:0.010000000000004719 eigen_vector:[1.00000000e+00 9.60980344e-09]
iter:4 eigen_value:0.01000000000000001 eigen_vector:[1.00000000e+00 9.51465688e-11]
iter:5 eigen_value:0.010000000000000009 eigen_vector:[1.00000000e+00 9.42045235e-13]
iter:6 eigen_value:0.010000000000000009 eigen_vector:[1.00000000e+00 9.32718055e-15]
iter:7 eigen_value:0.010000000000000009 eigen_vector:[1.00000000e+00 9.23483222e-17]
iter:8 eigen_value:0.010000000000000009 eigen_vector:[1.00000000e+00 9.14339824e-19]
iter:9 eigen_value:0.010000000000000009 eigen_vector:[1.00000000e+00 9.05286955e-21]
iter:10 eigen_value:0.010000000000000009 eigen_vector:[1.00000000e+00 8.96323718e-23]
iter:11 eigen_value:0.010000000

(1.0, array([1.00000000e+000, 3.69711212e-201]))