<a href="https://colab.research.google.com/github/shu65/theoretical-numerical-linear-algebra/blob/main/%E7%B7%9A%E5%BD%A2%E8%A8%88%E7%AE%97%E3%81%AE%E6%95%B0%E7%90%86_7_2_2_%E3%81%B9%E3%81%8D%E4%B9%97%E6%B3%95%E3%80%80%E9%80%86%E5%8F%8D%E5%BE%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a_matrix = np.array(
    [[1, 0],
     [0, 2]]
     )
a_matrix

array([[1, 0],
       [0, 2]])

In [ ]:
np.linalg.eig(a_matrix)

(array([1., 2.]), array([[1., 0.],
        [0., 1.]]))

In [ ]:
def lu_decompose(a):
  n = a.shape[0]
  l = a.copy()
  u = np.identity(n)
  for i in range(n):
    for j in range(i + 1, n):
      u[j][i] = l[j][i]/l[i][i]
      for k in range(i + 1, n):
        l[j][k] -= u[j][i] * l[i][k]
    return l, u

l, u = lu_decompose(a_matrix)
print("l", l)
print("u", u)

l [[1 0]
 [0 2]]
u [[1. 0.]
 [0. 1.]]


In [ ]:
np.testing.assert_almost_equal(a_matrix, l @ u)

In [ ]:
def l_solve(l, x):
  n = len(x)
  v = np.zeros(n)
  a = l.copy()
  b = x.copy()
  for i in range(n):
    tmp = b[i] / a[i, i]
    v[i] = tmp
    for j in range(i+1, n):
      b[j] -= a[j, i] *  tmp
      a[j, i] = 0
  return v

x = np.ones((a_matrix.shape[1],))/np.sqrt(a_matrix.shape[1]) 
v = l_solve(l, x)
v

array([0.70710678, 0.35355339])

In [ ]:
np.testing.assert_almost_equal(l @ v, x)

In [ ]:
def u_solve(u, v):
  n = len(v)
  y = np.zeros(n)
  a = u.copy()
  b = v.copy()
  for i in reversed(range(n)):
    tmp = b[i] / a[i, i]
    v[i] = tmp
    for j in range(i+1, n):
      b[j] -= a[j, i] *  tmp
      a[j, i] = 0
  return v

x = np.ones((a_matrix.shape[1],))/np.sqrt(a_matrix.shape[1]) 
y = u_solve(u, v)
y

array([0.70710678, 0.35355339])

In [ ]:
np.testing.assert_almost_equal(u @ y, v)

In [ ]:
def inverse_power_method(a, max_iterations=100):
  l, u = lu_decompose(a)
  eigen_vector = np.ones((a.shape[1],))/np.sqrt(a.shape[1])
  print("init eigen_vector", eigen_vector)
  for i in range(max_iterations):
    v = l_solve(l, eigen_vector)
    y = u_solve(u, v)
    inversed_eigen_value = np.linalg.norm(y)
    eigen_vector = y/inversed_eigen_value
    print(f"iter:{i} eigen_value:{1.0/inversed_eigen_value} eigen_vector:{eigen_vector}")
  return 1.0/inversed_eigen_value, eigen_vector

inverse_power_method(a_matrix)

init eigen_vector [0.70710678 0.70710678]
iter:0 eigen_value:1.2649110640673518 eigen_vector:[0.89442719 0.4472136 ]
iter:1 eigen_value:1.0846522890932808 eigen_vector:[0.9701425  0.24253563]
iter:2 eigen_value:1.0228166239135177 eigen_vector:[0.99227788 0.12403473]
iter:3 eigen_value:1.0058196417603769 eigen_vector:[0.99805258 0.06237829]
iter:4 eigen_value:1.0014623454071014 eigen_vector:[0.99951208 0.03123475]
iter:5 eigen_value:1.000366054554387 eigen_vector:[0.99987795 0.01562309]
iter:6 eigen_value:1.000091542956724 eigen_vector:[0.99996948 0.00781226]
iter:7 eigen_value:1.0000228875724326 eigen_vector:[0.99999237 0.00390622]
iter:8 eigen_value:1.0000057220076999 eigen_vector:[0.99999809 0.00195312]
iter:9 eigen_value:1.0000014305090872 eigen_vector:[9.99999523e-01 9.76562034e-04]
iter:10 eigen_value:1.0000003576277194 eigen_vector:[9.99999881e-01 4.88281192e-04]
iter:11 eigen_value:1.0000000894069578 eigen_vector:[9.99999970e-01 2.44140618e-04]
iter:12 eigen_value:1.000000022351

(1.0, array([1.00000000e+00, 7.88860905e-31]))