<a href="https://colab.research.google.com/github/shu65/theoretical-numerical-linear-algebra/blob/main/%E7%B7%9A%E5%BD%A2%E8%A8%88%E7%AE%97%E3%81%AE%E6%95%B0%E7%90%86_7_4_QR%E6%B3%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a_matrix = np.array([
      [1., 0., 0.,],
      [0., 2., 1.,],
      [0., 1., 1.],
  ])
a_matrix

array([[1., 0., 0.],
       [0., 2., 1.],
       [0., 1., 1.]])

In [2]:
expected_eigenvalues, expected_eigenvectors = np.linalg.eig(a_matrix)
print("expected eigenvalues:", expected_eigenvalues)
print("expected eigenvectors:")
print(expected_eigenvectors)

expected eigenvalues: [0.38196601 2.61803399 1.        ]
expected eigenvectors:
[[ 0.          0.          1.        ]
 [ 0.52573111 -0.85065081  0.        ]
 [-0.85065081 -0.52573111  0.        ]]


In [3]:
def qr_method(a, eps=1e-7, max_iterations=100):
  a_k = a
  q_km1 = np.identity(a_k.shape[0])
  for i in range(max_iterations):
    q_k, r_k = np.linalg.qr(a_k)
    relative_residual_norm = np.linalg.norm(q_km1 - q_k)
    if relative_residual_norm < eps:
      break
    a_k = r_k @ q_k
    q_km1 = q_k
  eigenvalues = np.diag(a_k)
  return eigenvalues

eigenvalues = qr_method(a_matrix)
print("eigenvalues:", eigenvalues)

eigenvalues: [1.         2.61803399 0.38196601]


In [4]:
def qr_method_with_eigenvectors(a, eps=1e-7, max_iterations=100):
  a_k = a
  n = a_k.shape[0]
  eigenvectors = np.identity(n)
  for i in range(max_iterations):
    q_k, r_k = np.linalg.qr(a_k)
    eigenvectors = np.dot(q_k, eigenvectors)
    a_kp1 = r_k @ q_k
    relative_residual_norm = np.linalg.norm(np.diag(a_kp1) - np.diag(a_k))
    if relative_residual_norm < eps:
      break
    a_k = a_kp1
  eigenvalues = np.diag(a_kp1)
  return eigenvalues, eigenvectors

eigenvalues, eigenvectors = qr_method_with_eigenvectors(a_matrix)
print("eigenvalues:", eigenvalues)
print("eigenvectors:")
print(eigenvectors)

eigenvalues: [1.         2.61803399 0.38196601]
eigenvectors:
[[ 1.          0.          0.        ]
 [ 0.          0.85065394  0.52572604]
 [ 0.         -0.52572604  0.85065394]]
